# Generated by Django 4.2.1 on 2023-06-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_friendshipreqeust'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendshipReqeust',
            new_name='FriendshipRequest',
        ),
    ]
